### ISSUE TITLE
Analyse av personvern i Smittestopp 2.0

### ISSUE THREAD

**Issue by tjesi** [folkehelseinstituttet/Fhi.Smittestopp.Documentation#4]
Analyse gjennomført sammen med @martstr. Vi foreslår en løsning for å randomisere tokens, slik at det ikke er mulig å knytte identitet til smittenøkler.

[Ytterligere forsterket personvern i Smittestopp 2.0.pdf](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Documentation/files/5488038/Ytterligere.forsterket.personvern.i.Smittestopp.2.0.pdf)

[Smittestopp_2_0__Vedlegg.pdf](https://github.com/folkehelseinstituttet/Fhi.Smittestopp.Documentation/files/5495471/Smittestopp_2_0__Vedlegg.pdf)

**Comment by tjesi** [comment]
En demo av protokollen vår er nå tilgjengelig i repoet [anonymous-tokens](https://github.com/tjesi/anonymous-tokens). Koden er på ca 100 linjer + kommentarer, fordelt over tre filer. All kode er skrevet i Go, og tar i bruk innebygde funksjoner i [crypto/elliptic](https://golang.org/pkg/crypto/elliptic) hvor det er mulig. Målet er at dette skal la seg oversette til C# uten altfor store problemer, og kunne inkluderes i Smittestopp 2.0 som en erstatning av dagens system for tokens.

**Comment by tjesi** [comment]
Vi holder på å implementere tilsvarende funksjonalitet i C# sammen med @HenrikWM. Flere bidrag er hjertelig velkommen, [sjekk ut koden her](https://github.com/HenrikWM/anonymous-tokens).

**Comment by sindremb** [comment]
Dette er et spennende initiativ.

Dagens flyt fungerer grovt sett slik:
1. Bruker verifiseres mot verifiseringsløsing og app får tilbake token A
2. App henter ut diagnosenøkler fra GAEN, og legger til smittesomhetsinfo basert på info fra bruker + token A
3. App laster opp diagnosenøkler til backend med token A

Vil en ny flyt som tar hensyn til dette dokumentet kunne fungere noe slikt?
1. Bruker verifiseres mot verifiseringsløsing og app får tilbake token A
2. App henter ut diagnosenøkler fra GAEN, og legger til smittesomhetsinfo basert på info fra bruker + token A
3. App gjør kall til verifiseringsløsning med token A for å hente ny token B basert på vedlagt dok
4. App laster opp diagnosenøkler til backend med token B

Men en slik flyt så vil det meste av logikk før faktisk opplastning være identisk med det som allerede er implementert, men selve opplastningen fra app må utvides, og backend må endre sin auth-logikk.

**Comment by tjesi** [comment]
Flyten er faktisk den samme i dagens system og i vårt forslag. Det nye token B kan appen beregne selv basert på token A. Den trenger altså ikke ta kontakt med verifiseringsløsningen for å få tak i denne.

Det stemmer forøvrig at måten token genereres og verifiseres må endres, ettersom token som sendes er noe annet enn i dagens løsning. Det er derimot bare små forskjeller, og både lokale beregninger og datamengde som sendes til være av samme størrelsesorden som i dag.

Dersom du ser på demoen eg skrev i Go, så vil det være appen som kjører Initiate() og RandomiseToken(), det er verifiseringsløsningen som kjører GenerateToken() og det er backend som kjører VerifyToken() på følgende vis:

1. Bruker genererer et nonce og verifiseres mot verifiseringsløsing: Initiate
2. Verifiseringsløsing generer et token A og et bevis, og sender begge til app: GenerateToken
3. App verifiserer bevis og randomiserer token A lokalt for å få token B: RandomiseToken
4. App henter ut diagnosenøkler fra GAEN, og legger til smittesomhetsinfo basert på info fra bruker
5. App laster opp diagnosenøkler til backend med token B, som så verifiseres: VerifyToken

**Comment by tjesi** [comment]
Spørsmål: Du skriver at "App henter ut diagnosenøkler fra GAEN, og legger til smittesomhetsinfo basert på info fra bruker + token A". Betyr dette at token A skal sendes til GAEN og verifiseres før smittenøkler returneres til appen? 

Vår analyse har tatt utgangspunkt i at Smittestopp.Verification er den som utsender token, og at Smittestopp.Backend verifiserer token, men at GAEN opererer uavhengig av dette.

**Comment by sindremb** [comment]
Token A i dette tilfellet inneholder claim for bl.a. prøvedato. Dette blir brukt som fallback hvis bruker ikke kan eller vil oppgi dato for "onset of symptoms". Dette blir så igjen brukt til å tagge hver daglige "diagnosenøkkel" med en risk-level (GAEN v1, beregnet ut fra feks onset of symptoms) og/eller "days since onset of symptoms" (GAEN v1.5+, brukes for å la hver app beregne sin egen risk-level). Dette er da for at man typisk skal kunne si at diagnose nøkler fra og med 2 dager før symptomer til og med 7 dager etter, skal kunne gi varsel om smittekontakt. v1.5 har endret på dette slik at hvert enkelt land kan ta sin egen bestutning på dette også for nøkler man får fra andre land.

Så backend er egentlig ikke avhengig av info i token A, så lenge den har en annen måte å sjekke at opplastningen er gyldig.

Hvordan kan vi håndtere token replay attacks med slike randomiserte tokens? Vil token B alltid bli lik for en gitt token A, eller vil disse kunne variere? Noe annet backend kan bruke til å fange opp at en token B stammer fra samme token A?

**Comment by martstr** [comment]
Dette med datofesting har vi tatt høyde for ved å si at man kan forhåndsgenerere nøkler for hver dag. Den nøkkelen som er brukt for å generere et token, gir også en entydig dato. Dersom personen har prøvedato a, brukes nøkkel k_a, hvis det er prøvedato b, brukes nøkkel k_b, etc.  Er det mer info som er tenkt inkludert?

Så var det replay-angrep. Det er et veldig godt spørsmål. Jeg har touchet innpå det i et svar til E.S. i #general i smittestopp-innsyn-slacken. Kort sagt er svaret på spørsmål 2 "ja": Token B er entydig bestemt av token A, men på en måte som er helt utforutsigbar. Når token B sendes inn sendes også den underliggende generatoren for tokenet, og det er denne som arkiveres (etter at den er verifisert) for å forhindre replay.

**Comment by sindremb** [comment]
For datomerkingen/riskscoring av hver diagnosenøkkel. Referer k_a, k_b, .. til forskjellige k-nøkler (ref kommentar #general i smittestopp-innsyn) som brukes i verifiseringsløsningen og backend? I så fall tror jeg dette er enklere å løse ved a bare bruke en felles k, og at denne informasjonen bare blir med som info i opplastningen? Det er jo bare appen som vet hvilke dag en diagnosenøkkel gjelder for, backend trenger bare vite diagnosenøkkelens risk level og/eller antall dager relativt til dag for symptomer. Så er det opp til hver enkelt telefon å koble diagnosenøkkelen tilbake til en kontaktdato når de får en match mot en tilhørende kontaktnøkkel de har registrert (med tidspunkt og signalstyrke).

Angående replay attack. Forstår det da som at backend da lagrer T (ref kommentar #general i smittestopp-innsyn) for å fange opp token replay? Er det noe mulighet for å få inkludert begrenset gyldighetsperiode for en nøkkel, eller må T lagres i evig tid i backend? Hva er sannsynligheten for kollisjon på T? Det er gjerne her vi heller bruker k_a, k_b,.. for å scope sjekk av T mot replay attacks? Dette vil kreve en mekanisme som sørger for at backend og verifiseringsløsningen hele tiden er i sync på hvilke k_x som er gyldige, men det skal vel ikke være uoverkommelig.

**Comment by martstr** [comment]
Nøklene k_a og k_b jeg nevnte over var bare for å si at man kunne lage systemet slik at nøkkelvalget avhang av prøvedato, ikke dato for innsending. Verifiseringsløsningen og backend har samme nøkkel(-sett).

Grunnen til at vi tenkte å kode datoen i nøkler var for å forsvare mot at appen kunne lyve på datoen, men siden dette uansett kan overstyres av at brukeren oppgir en dato for symptomer, så har det nok ikke så mye å si. Da er det enklere å bruke samme nøkkel over en lang periode. (Det ligger i vår natur, vi tenker alltid det verste om alle ...)

Replay: Backend lagrer _t_, siden det er den som genererer det hele. Dersom man skifter ut nøkkelen _k_ kan man også slette loggen over tidligere lagrede _t_, siden tidligere token ikke lenger vil være gyldige.

Siden det å bruke nøkkel for å formidle info om dato ikke er nødvendig er det antageligvis ingenting i veien for å ha nøkler med lang gyldighet. I praksis vil det jo også være kort tid mellom at et token utstedes og at det blir brukt (i praksis snakker vi vel minutter?), så nøkkelrullering bør kunne gå ganske greit. Det vesentlige er at det også distribueres en ny offentlig nøkkel som appen bruker for å verifisere at det tokenet den får fra verifiseringsløsningen ikke er noe annet enn det utgir seg for å være.

**Comment by martstr** [comment]
Etter oppfordring, skissen til hvordan dette fungerer:

1. Appen lager et tilfeldig tall t, og lager et punkt T på den elliptiske kurven fra dette.
2. Appen maskerer T med et tilfeldig tall r
3. Verifikasjonsserveren får et tilsynelatende tilfeldig kurvepunkt fra appen. Dersom personen er smittet, så maskerer serveren dette punktet med en nøkkel k. I tillegg lager serveren et fancy zero-knowledge-bevis for at den faktisk har brukt k, men uten å røpe k.
4. Appen får tilbake punktet T som nå er maskert av både r og k, og fjerner r-maskeringen, fortsatt uten å lære noe om k. Det nye punktet sendes til Smittestopp-backend sammen med det tilfeldige tallet t.
5. Backend lager T fra t på samme måte som appen gjorde det, og maskerer T med samme k som den andre serveren hadde. Dersom serveren da får samme resultat som det brukeren sendte inn er det helt sikkert* at verifikasjonsserveren har gått god for at denne brukeren er smittet.

*) Bortsett fra en sannsynlighet som tilsvarer å vinne førstepremien i Lotto 11-12 uker på rad ...

**Comment by tjesi** [comment]
**Noen små bemerkning angående kollisjoner og lagring av token:**

For å hindre replay så lagrer man t, og sjekker at denne ikke forekommer mer enn en gang. t er en tilfeldig streng av lengde B bytes, hvor vi bestemmer B. Sannsynligheten for kollisjoner, gitt at t genereres tilfeldig, er mindre enn (1/2)^(4*B). Vi har i utgangspunktet satt B = 32, så denne sannsynligheten er neglisjerbar og kollisjoner vil i praksis aldri forekomme. Data som må lagres er da 32 Bytes per smittetilfelle som rapporteres med gyldig token.

Dersom man bytter offentlig nøkkel på et tidspunkt, feks hver uke eller hver mnd, så blir alle tidligere tokens ugyldige. Da kan man slette alle verdier t man har mottatt, og alle nye tokens sjekkes mot den nye nøkkelen før de så lagres.

**Angående offentlige nøkler:**

Det virker som at det er unødvendig å ha smittenøkler k_a, k_b,... osv for hver dato, og at man velger en av disse basert på når man testet positivt. Dette gir ikke mening når det uansett er appen som vet når en diagnosenøkkel er gyldig. Da er det bedre å ha en offentlig nøkkel k som er gyldig for en gitt tidsperiode, feks en uke eller en mnd, som så kan oppdateres. Da slipper man å lagre tokens for alltid, og man sikrer oss at den positive prøven var tatt nylig, selv om man ikke vet akkurat hvilken dato.

**Comment by sindremb** [comment]
Beklager at jeg ikke har svart på denne raskere.

Det er ikke GAEN som trenger token A, men appen som henter ut TEKs fra GAEN, og så kombinerer disse med smittsomhetsinfo basert på input fra bruker, samt info om prøvedato i token A.

Jeg tror den aller enkleste veien til mål er å beholde dagens implementasjon slik den er helt from til steget rett før appen laster opp nøklende, hvor vi så introduserer anonyme nøkler på følgende måte.

1. Utvid verifiseringsløsning med nytt endepunkt som lar appen bytte ut en "token A" med en anonym "token X"
2. Utvide backend til å kunne verifisere opplastning ved hjelp av "token X" (gjerne som en tilleggsalternativ til token A i første fase)
3. Endre appen gjøre kall mot verifiseringsløsningen for å bytte ut "token A" med ny anonym "token X", og bruke dette i stedet ved opplastning.

**Comment by tjesi** [comment]
Noen spørsmål:
- Hvordan er det token A genereres i dag? Hvilken informasjon er inkludert?
- Inntrykket mitt er at det er en kryptografisk signatur. Stemmer det? 
- Sendes det også info om prøvedato? Mer? Hvordan?

**Comment by martstr** [comment]
Jeg må innrømme at jeg ikke helt forsto beskrivelsen din, @sindremb, så jeg prøvde å tegne den. Er dette riktig forstått?
![20201120_003213](https://user-images.githubusercontent.com/16204818/99737381-77ffa300-2ac8-11eb-852e-e2c3e054ab15.jpg)
(ID er en forenkling av at den går via ID-porten.)

For kompletthet, her er den ideelle flyten med våre tokens.
![20201120_003225](https://user-images.githubusercontent.com/16204818/99737387-78983980-2ac8-11eb-933d-b43ce54a9311.jpg)

**Comment by OsirisTerje** [comment]
@tjesi Any chance of getting the documents you have written (links at top) in English versions ?

**Comment by martstr** [comment]
They are currently not available in English. Which part is most relevant? Much of the same content is also available in our wiki: https://github.com/HenrikWM/anonymous-tokens/wiki

**Comment by netcompany-martinropcke** [comment]
I'll close this issue as it has been implemented quite a while ago
